name: peslearn-docs
channels:
    - nodefaults
    - conda-forge
dependencies:
    - python=3.8
    - sphinx
    - sphinx_rtd_theme
    - sphinx-automodapi
    - sphinx-autodoc-typehints
    - autodoc-pydantic
    
      # PESLearn depends
    - numpy
    - pydantic >=0.30.1
    - qcelemental >=0.9.0
    - numpy >=1.7
    - GPy >=1.9
    - scikit-learn >=0.20
    - pandas >=0.24
    - hyperopt >=0.1.1
    - cclib >=1.6
    - torch >=1.0.1
    - joblib >=1.3.0
    - qcelemental >=0.27.1
    - qcengine >=0.26.0